# Generated by Django 3.0.6 on 2020-06-15 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0020_auto_20200603_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number_verify_code',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
