# Generated by Django 3.0.6 on 2020-06-16 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0021_auto_20200615_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='visited_pages_count',
            field=models.IntegerField(default=1),
        ),
    ]
