# Generated by Django 3.0.6 on 2020-06-15 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('creative_shop', '0012_auto_20200603_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='delivery_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_method', to='creative_shop.DeliveryMethod'),
        ),
        migrations.AddField(
            model_name='card',
            name='order_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='payed',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='carditem',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='activedeliverymethods',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_delivery_methods', to='creative_shop.Shop'),
        ),
        migrations.AlterField(
            model_name='card',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='creative_shop.Shop'),
        ),
        migrations.AlterField(
            model_name='card',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='carditem',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='creative_shop.Card'),
        ),
        migrations.AlterField(
            model_name='carditem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='creative_shop.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='creative_shop.ProductCategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo_filename',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='creative_shop.Shop'),
        ),
    ]
